<?php
include("tag_a.html")
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="moket.css">
</head>
<table style="width:100%">
  <tr>
    <th>ردیف</th>
    <th>نام محصول</th> 
    <th>کد محصول</th>
    <th>(ریال) قیمت محصول</th>
  </tr>
  <tr>
    <td> 1</td>
    <td>الماس</td> 
    <td>132</td>
    <td>10,692,680</td>
  </tr>
  <tr>
    <td>2</td>
    <td>یاس</td> 
    <td>129</td>
    <td>8,727,520</td>
  </tr>
  <tr>
    <td>3</td>
    <td>دالیا</td> 
    <td>108</td>
    <td>7,873,070</td>
  </tr>
  <tr>
    <td>4</td>
    <td>صنویر</td> 
    <td>199</td>
    <td>7,873,070</td>
  </tr>
  <tr>
    <td>5</td>
    <td>ونوس</td> 
    <td>207</td>
    <td>7,873,070</td>
  </tr>
  <tr>
    <td>6</td>
    <td>یاسمن</td> 
    <td>164</td>
    <td>5,438,660</td>
  </tr>
  <tr>
    <td>7</td>
    <td>لیندا</td> 
    <td>105</td>
    <td>4,889,740</td>
  </tr>
  <tr>
    <td>8</td>
    <td>راش</td> 
    <td>167</td>
    <td>4,549,660</td>
  </tr>
  <tr>
    <td>9</td>
    <td>پتینه</td> 
    <td>208</td>
    <td>4,549,660</td>
  </tr>
  <tr>
    <td>10</td>
    <td>افرا</td> 
    <td>205</td>
    <td>4,101,360</td>
  </tr>
  <tr>
    <td>11</td>
    <td>باران</td> 
    <td>206</td>
    <td>3,732,980</td>
  </tr>
  <tr>
    <td>12</td>
    <td>خزان</td> 
    <td>118</td>
    <td>3,696,520</td>
  </tr>
  <tr>
    <td>13</td>
    <td>کات B</td> 
    <td>326</td>
    <td>3,551,380</td>
  </tr>
  <tr>
    <td>14</td>
    <td>نیلوفر</td> 
    <td>109</td>
    <td>3,541,370</td>
  </tr>
  <tr>
    <td>15</td>
    <td>پامچال</td> 
    <td>411</td>
    <td>3,410,760</td>
  </tr>
  <tr>
    <td>16</td>
    <td>شبنم</td> 
    <td>149</td>
    <td>2,839,450</td>
  </tr>
  <tr>
    <td>17</td>
    <td>پونه</td> 
    <td>442</td>
    <td>2,760,970</td>
  </tr>
  <tr>
    <td>18</td>
    <td>زبیا</td> 
    <td>103</td>
    <td>2,610,220</td>
  </tr>
</table>
</body>
</html>
<?php
include("footer2.html")
?>
